### ISSUE TITLE
Fabric 1.19 server crashes on startup with REI

### ISSUE THREAD

**Issue by Zennii** [LordDeatHunter/Musica#5]
REI doesn't seem to like this mod, server crashes on startup with the following error:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.7.jar:?]
 at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
 at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.7.jar:?]
 at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.7.jar:?]
 at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.0]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
 at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
 at com.sun.proxy.jdk.proxy3.$Proxy27.onInitialize(Unknown Source) ~[?:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.7.jar:?]
 ... 8 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Musica. Please use "rei_server", "rei_client" or "rei_common" instead.
 at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:53) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:107) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:136) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.PluginDetector.detectCommonPlugins(PluginDetector.java) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:153) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.0.475.jar:?]
 at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
 at com.sun.proxy.jdk.proxy3.$Proxy27.onInitialize(Unknown Source) ~[?:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.7.jar:?]
 ... 8 more
```

I initially looked into where the error message sourced from, thinking it was something I had to do. But it appears to be a tip for developers? So I thought you might want to see this. Specifically the `Rerached side issue when loading REI plugin by Musica. Please use "rei_server", "rei_client" or "rei_common" instead.`

REI version `9.0.475`
Wraith Musica version `1.5.2`
MC version `1.19`
Fabric loader version `0.14.7`
Fabric launcher version `0.11.0`

**Comment by LordDeatHunter** [comment]
Hmm, odd... I thought I took care of that...
Noted, will look into it when I have time in the following days.
